version: '3.8'

services:
  inference-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ~/inference-server/models:/service/model
      - ~/inference-server/logs:/service/logs
    environment:
      - PROD_SERVER=https://jrkenyomxwtanrwiyrha.supabase.co/functions/v1/set-analysis
      - DEV_SERVER=https://dsgmzpmadgogiksffrpc.supabase.co/functions/v1/set-analysis
      - VIRTUAL_host=inference-server.darkflow.com.ar
    restart: always
    container_name: inference-server